# The calibration harness's own logic.
#
# `inst/memory/calibrate.R` decides the constants the guard ships with, so
# a bug in it is a bug in every estimate, and a quiet one: everything
# still runs, the numbers are just wrong. Three real bugs turned up in it
# by accident during the first calibration -- an optimiser settling in a
# flat valley, a reinstall being mistaken for a crash boundary, a floor
# subtraction that made TabFM's ensemble factor come out at 14. These are
# the regression tests for that class of mistake.
#
# Only the pure parts are exercised: grid construction, point
# classification, and the two fits. Nothing here launches a worker or
# touches a checkpoint.

skip_if_not_installed("jsonlite")

harness_path <- tabfound:::tabfound_file("memory", "calibrate.R")
skip_if(!nzchar(harness_path), "calibration harness not installed")

cal <- new.env(parent = globalenv())
suppressWarnings(sys.source(harness_path, envir = cal))

# A point in the shape `fit_coefs()` wants: two stages, so the max over
# them is actually exercised.
cal_point <- function(peak, act, att = c(0, 0), fixed = 0,
                      status = "ok", n_context = 1000, loaded = 4e8) {
  list(peak_bytes = peak, act = act, att = att,
       weights_bytes = fixed, persistent_bytes = 0,
       status = status, n_context = n_context, n_features = 10,
       n_query = 100, loaded_bytes = loaded)
}

# Peaks generated by a known intercept and slope, so the fit has a right
# answer to find.
synthetic_rows <- function(intercept = 1.5e9, copies = 100, n = 8) {
  acts <- 1e6 * (2^seq_len(n))
  lapply(seq_len(n), function(i) {
    peak <- intercept + 4 * copies * acts[i]
    cal_point(peak, act = c(acts[i], acts[i] / 3),
              n_context = 100 * 2^i)
  })
}


# ---------------------------------------------------------------------------
# Sourcing it must not run it
# ---------------------------------------------------------------------------

test_that("sourcing the harness does not start a calibration", {
  # It did once: the entry-point guard read `!interactive()`, which is
  # true under `sys.source()` too, so loading the file to reuse one
  # function silently began measuring every backend.
  expect_true(is.function(cal$fit_coefs))
  expect_true(is.function(cal$measure_point))
  expect_true(is.function(cal$build_grid))
})


# ---------------------------------------------------------------------------
# The grid
# ---------------------------------------------------------------------------

test_that("the grid covers both dimensions and runs cheapest first", {
  g <- cal$build_grid("small")
  expect_gt(length(g), 4L)
  cost <- vapply(g, function(p) p$n_context * p$n_features, numeric(1))
  # Interrupting a run should leave a usable spread, not one corner.
  expect_false(is.unsorted(cost))
  expect_gt(length(unique(vapply(g, function(p) p$n_context, numeric(1)))), 1L)
  expect_gt(length(unique(vapply(g, function(p) p$n_features, numeric(1)))), 1L)
})

test_that("an unknown grid name is refused rather than silently empty", {
  expect_error(cal$build_grid("enormous"), "unknown grid")
})


# ---------------------------------------------------------------------------
# Which points count
# ---------------------------------------------------------------------------

test_that("a point that never ran is not mistaken for a crash boundary", {
  # The distinction that matters most: a worker killed by the allocator
  # is a finding, and a worker that could not load the package is a bug.
  # Treating the second as the first bakes a fictional ceiling into the
  # constants.
  rows <- list(
    cal_point(5e9, c(1e6, 1e5)),
    cal_point(NA_real_, c(1e6, 1e5), status = "error"),
    cal_point(NA_real_, c(1e6, 1e5), status = "no_start")
  )
  expect_length(cal$failed_points(rows), 2L)
  expect_length(cal$usable_points(rows), 1L)
  # An errored point is neither usable nor a ceiling observation.
  expect_length(cal$censored_points(rows), 0L)
})

test_that("a point that died is recorded as a ceiling, not as a value", {
  rows <- list(cal_point(5e9, c(1e6, 1e5)),
               cal_point(30e9, c(2e6, 2e5), status = "died"))
  expect_length(cal$usable_points(rows), 1L)
  expect_length(cal$censored_points(rows), 1L)
})

test_that("a point near the machine's ceiling is treated as a lower bound", {
  withr::local_envvar(TABFOUND_CENSOR_FRACTION = "0.6")
  total <- tabfound:::.system_memory()$total
  skip_if(!isTRUE(is.finite(total)), "cannot probe this machine")
  rows <- list(cal_point(0.1 * total, c(1e6, 1e5)),
               cal_point(0.9 * total, c(9e6, 9e5)))
  expect_length(cal$usable_points(rows), 1L)
  expect_length(cal$censored_points(rows), 1L)
})


# ---------------------------------------------------------------------------
# Fitting
# ---------------------------------------------------------------------------

test_that("the fit recovers constants it was given", {
  rows <- synthetic_rows(intercept = 1.5e9, copies = 100)
  co <- cal$fit_coefs(rows, baseline = 4e8)
  expect_equal(co$act_copies, 100, tolerance = 0.02)
  expect_equal(co$intercept_bytes, 1.5e9, tolerance = 0.05)
  expect_lt(co$att_copies, 1)
  # Nothing to be safe about when the model is exact.
  expect_equal(co$safety_factor, 1, tolerance = 0.01)
})

test_that("the fit does not settle in the flat valley it once did", {
  # The failure this replaces: from a single start, `optim()` chose an
  # intercept of 100 MB where the data wanted 1.7 GB and inflated the
  # slope to compensate -- silently, and only visible as ratios drifting
  # from 1.0 to 3.2 across the grid.
  rows <- synthetic_rows(intercept = 3e9, copies = 60)
  co <- cal$fit_coefs(rows, baseline = 4e8)
  expect_gt(co$intercept_bytes, 2e9)
  expect_equal(co$act_copies, 60, tolerance = 0.05)
})

test_that("the safety factor lifts the fit above every measured point", {
  # The invariant the guard rests on: over-estimating costs a warning,
  # under-estimating costs the session.
  rows <- synthetic_rows()
  # Push one point above what any smooth fit can reach.
  rows[[3]]$peak_bytes <- rows[[3]]$peak_bytes * 1.6
  co <- cal$fit_coefs(rows, baseline = 4e8)
  expect_gt(co$safety_factor, 1)
  expect_true(all(co$predicted * co$safety_factor >= co$measured * (1 - 1e-9)))
})

test_that("the intercept is not allowed below the measured baseline", {
  # The peak cannot be smaller than what was already resident when the
  # weights finished loading.
  rows <- synthetic_rows(intercept = 5e8, copies = 100)
  co <- cal$fit_coefs(rows, baseline = 2e9)
  expect_gte(co$intercept_bytes, 2e9)
})

test_that("the fit runs through the package's own assembly function", {
  # If the fitter and `estimate_peak_memory()` ever evaluate different
  # expressions, the constants stop meaning anything and nothing says so.
  rows <- synthetic_rows()
  co <- cal$fit_coefs(rows, baseline = 4e8)
  coefs <- list(intercept_bytes = co$intercept_bytes,
                act_copies = co$act_copies, att_copies = co$att_copies,
                safety_factor = 1)
  direct <- tabfound:::.peak_from_terms(
    list(list(name = "a", act = rows[[1]]$act[1], att = rows[[1]]$att[1]),
         list(name = "b", act = rows[[1]]$act[2], att = rows[[1]]$att[2])),
    rows[[1]]$weights_bytes, rows[[1]]$persistent_bytes, coefs,
    spmf = 1, n_estimators = 1
  )$peak
  expect_equal(direct, co$predicted[1])
})


# ---------------------------------------------------------------------------
# Extrapolation
# ---------------------------------------------------------------------------

test_that("the holdout refits without the largest sizes and predicts them", {
  rows <- synthetic_rows(n = 8)
  h <- cal$holdout_check(rows, baseline = 4e8)
  expect_false(is.null(h))
  expect_gt(length(h$points), 0L)
  # Every held-out point must be above the cut it was held out at.
  expect_true(all(vapply(h$points, function(p) p$n_context, numeric(1)) >=
                    h$held_out_from))
  # On data the model fits exactly, extrapolation is exact.
  expect_equal(unname(h$predicted / h$measured),
               rep(1, length(h$measured)), tolerance = 0.05)
})

test_that("too few sizes means no holdout rather than a meaningless one", {
  rows <- synthetic_rows(n = 3)
  rows <- lapply(rows, function(r) { r$n_context <- 1000; r })
  expect_null(cal$holdout_check(rows, baseline = 0))
})


# ---------------------------------------------------------------------------
# The ensemble sweep
# ---------------------------------------------------------------------------

ensemble_rows <- function(peaks, n = c(1L, 2L, 4L, 8L)) {
  lapply(seq_along(peaks), function(i) {
    r <- cal_point(peaks[i], c(1e7, 1e6))
    r$n_estimators <- n[i]
    r
  })
}

test_that("the ensemble envelope covers every member count measured", {
  skip_if(is.null(tabfound:::.memory_coefs("tabicl", "cpu")), "no coefficients")
  sweep <- list(backend = "tabicl", point = list(n_context = 800,
                                                 n_query = 500,
                                                 n_features = 32),
                rows = ensemble_rows(c(3e9, 3.6e9, 5.5e9, 5.8e9)))
  co <- tabfound:::.memory_coefs("tabicl", "cpu")
  config <- mem_config_tabicl()
  ef <- cal$ensemble_factor(sweep, co, 1.1e8, config)
  expect_false(is.null(ef))
  expect_true(all(ef$envelope >= ef$ratios - 1e-9))
  expect_equal(ef$envelope[1], 1)
  expect_gt(ef$k, 0)
})

test_that("the ensemble factor uses differences, not a modelled floor", {
  # Subtracting `intercept + weights` was the first attempt, and for
  # TabFM it left a 0.5 GB "transient" and an implied factor of 14.
  # Adding a constant to every peak must not change the answer.
  skip_if(is.null(tabfound:::.memory_coefs("tabicl", "cpu")), "no coefficients")
  co <- tabfound:::.memory_coefs("tabicl", "cpu")
  config <- mem_config_tabicl()
  point <- list(n_context = 800, n_query = 500, n_features = 32)
  peaks <- c(3e9, 3.6e9, 5.5e9, 5.8e9)

  a <- cal$ensemble_factor(list(backend = "tabicl", point = point,
                                rows = ensemble_rows(peaks)),
                           co, 1.1e8, config)
  b <- cal$ensemble_factor(list(backend = "tabicl", point = point,
                                rows = ensemble_rows(peaks + 9e9)),
                           co, 1.1e8, config)
  expect_equal(a$k, b$k)
  expect_equal(a$ratios, b$ratios)
})

test_that("a sweep with no single-member point yields no factor", {
  skip_if(is.null(tabfound:::.memory_coefs("tabicl", "cpu")), "no coefficients")
  sweep <- list(backend = "tabicl",
                point = list(n_context = 800, n_query = 500, n_features = 32),
                rows = ensemble_rows(c(3.6e9, 5.5e9, 5.8e9),
                                     n = c(2L, 4L, 8L)))
  expect_null(cal$ensemble_factor(sweep, tabfound:::.memory_coefs("tabicl", "cpu"),
                                  1.1e8, mem_config_tabicl()))
})
